version: '3.8'

services:

  notion_watcher:
    container_name: notion_watcher
    hostname: notion_watcher
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/NotionWatcher/.env
      - ./data/watchers:/NotionWatcher/watchers
      - ./data/data:/NotionWatcher/data
      - ./data/logs:/NotionWatcher/logs
