version: '3.8'

services:

  notion_watcher:
    container_name: notion_watcher
    hostname: notion_watcher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NW_ENV=production
    volumes:
      - ./.env:/NotionWatcher/.env
      - ./data:/NotionWatcher/data
