version: '3.8'

services:

  # REST API server
  notion_watcher:
    container_name: notion_watcher
    hostname: notion_watcher
    #command: cat /nw/.env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NW_ENV=production
      - LOG_LEVEL=debug
    volumes:
      - ./.env:/nw/.env
      - ./data:/nw/data